"""Signal model — the core data structure emitted by all strategies."""

from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, Field, field_validator


class Direction(StrEnum):
    LONG = "LONG"
    SHORT = "SHORT"


class Signal(BaseModel):
    """A trading signal generated by a strategy.

    This is the universal output format for all algorithms. Each signal contains
    everything needed to execute a trade on micro contracts.
    """

    strategy: str = Field(description="Strategy that generated this signal")
    symbol: str = Field(description="Full contract symbol (e.g., 'ES')")
    micro_symbol: str = Field(description="Micro contract symbol for execution (e.g., 'MES')")
    direction: Literal["LONG", "SHORT"]
    entry_price: float = Field(gt=0)
    stop_loss: float = Field(gt=0)
    take_profit: float | None = Field(default=None, description="None for trailing-stop-only exits")
    contracts: int = Field(gt=0, description="Number of micro contracts")
    risk_dollars: float = Field(gt=0, description="Dollar risk for this trade")
    timeframe: str = Field(description="e.g., '5m', '1h', '1d'")
    timestamp: datetime
    expiry: datetime | None = Field(
        default=None, description="Signal expires if not filled by this time"
    )
    confidence: float = Field(ge=0.0, le=1.0, description="From validation metrics")
    metadata: dict[str, Any] = Field(default_factory=dict)

    @field_validator("stop_loss")
    @classmethod
    def stop_loss_consistent_with_direction(cls, v: float, info: Any) -> float:
        """Validate stop loss is on the correct side of entry price."""
        entry = info.data.get("entry_price")
        direction = info.data.get("direction")
        if entry is not None and direction is not None:
            if direction == "LONG" and v >= entry:
                raise ValueError("Stop loss must be below entry for LONG signals")
            if direction == "SHORT" and v <= entry:
                raise ValueError("Stop loss must be above entry for SHORT signals")
        return v

    @field_validator("take_profit")
    @classmethod
    def take_profit_consistent_with_direction(cls, v: float | None, info: Any) -> float | None:
        """Validate take profit is on the correct side of entry price."""
        if v is None:
            return v
        entry = info.data.get("entry_price")
        direction = info.data.get("direction")
        if entry is not None and direction is not None:
            if direction == "LONG" and v <= entry:
                raise ValueError("Take profit must be above entry for LONG signals")
            if direction == "SHORT" and v >= entry:
                raise ValueError("Take profit must be below entry for SHORT signals")
        return v

    def to_json(self) -> str:
        """Serialize to JSON string."""
        return self.model_dump_json(indent=2)

    def risk_reward_ratio(self) -> float | None:
        """Calculate risk:reward ratio. Returns None if no take profit."""
        if self.take_profit is None:
            return None
        risk = abs(self.entry_price - self.stop_loss)
        reward = abs(self.take_profit - self.entry_price)
        if risk == 0:
            return None
        return reward / risk
